anchor_version = "0.24.2"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_stake_pool = "7R4GT7nP8A42upBNcSv1CUz2tDrFE8oezuWX2PojTo8R"
cardinal_reward_distributor = "8qYb1jcU4Q9hAms5VtoU2QFRrX37UEYBduCi4EEtojz7"

[programs.devnet]
cardinal_stake_pool = "7R4GT7nP8A42upBNcSv1CUz2tDrFE8oezuWX2PojTo8R"
cardinal_reward_distributor = "8qYb1jcU4Q9hAms5VtoU2QFRrX37UEYBduCi4EEtojz7"

[programs.testnet]
cardinal_stake_pool = "7R4GT7nP8A42upBNcSv1CUz2tDrFE8oezuWX2PojTo8R"
cardinal_reward_distributor = "8qYb1jcU4Q9hAms5VtoU2QFRrX37UEYBduCi4EEtojz7"

[programs.localnet]
cardinal_stake_pool = "7R4GT7nP8A42upBNcSv1CUz2tDrFE8oezuWX2PojTo8R"
cardinal_reward_distributor = "8qYb1jcU4Q9hAms5VtoU2QFRrX37UEYBduCi4EEtojz7"
